# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "localhost:4000/blog" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: shogonir
github_username:  shogonir



title: shogonir blog
name: shogonir
email: shogonir@gmail.com
description: Tech blog written by shogonir.

theme: jekyll-material-theme

parallax_image_one: assets/images/default/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/default/startup3.jpg

# Settings for the porfolio section

portfolio_heading: Portfolio
portfolio_type: cards #cards or carousel

project_one: "OZu"
project_one_description: "I represented OZ world of 'Summer Wars'!"
project_one_url: http://shogonir.jp/unity/ozu
project_one_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

project_two: "Mechanical Watch Movement"
project_two_description: "I represented mechanical watch movement with Unity."
project_two_url: http://shogonir.jp/unity/mwm
project_two_icon: location_on # these are from materiailize css, the full collection is here: http://materializecss.com/icons.html

# project_three: Third Project
# project_three_description: Describe your project!
# project_three_url: https://github.com/jameshamann/jekyll-material-theme
# project_three_icon: hotel

# project_four: Fourth Project
# project_four_description: Describe your project!
# project_four_url: https://github.com/jameshamann/jekyll-material-theme
# project_four_icon: restaurant

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: linux
  - name: android
  - name: vim
  - name: docker
  - name: git
  - name: github
  - name: c
  - name: cplusplus
  - name: csharp
  - name: python
  - name: go
  - name: java
  - name: javascript
  - name: typescript
  - name: nodejs
  - name: mocha
  - name: babel
  - name: webpack

icon_size: 36 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Unity

github: https://github.com/shogonir

# baseurl: # If your site is located at /blog or /home, change it here, otherwise leave it empty
# url: http://localhost:4000/ # The URL of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookie_accept_message: Thanks! # The pop-up dialog that appears after accepting the cookie notice.

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options â€º https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
      line_format: '%2i'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
